/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication21;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

public class frmTraductor extends javax.swing.JFrame {

    /**
     * Creates new form frmTraductor
     */
    public frmTraductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTraducir = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("Traductor de Español a Braile");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Ingrese el texto a traducir");

        txtTraducir.setColumns(20);
        txtTraducir.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        txtTraducir.setRows(5);
        jScrollPane1.setViewportView(txtTraducir);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("Traducir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(457, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(430, 430, 430)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(435, 435, 435)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addGap(21, 21, 21)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static void escribir(String ar){
        File miDir=new File(".");
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
            fichero = new FileWriter("traductor.html", false);
            fichero.write(ar);
            
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                //Nuevamente aprobechamos el finally para
                //asegurarnos que se cierra el fichero
                if (null != fichero) {
                    fichero.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
    }

    static String linea;
    static String archivoAt="";
    public static String leer() {
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;
        File miDir=new File(".");
        String lin = "";
        try {
            //Apertura del fichero y creacion de BufferedReader para poder
            //hacer una lectura comoda(disponer del metodo readLine()).
            archivo = new File(miDir.getCanonicalPath()+"\\traductor.html");
            archivoAt=""+miDir.getCanonicalPath()+"\\traductor.html";
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);
            
            //lectura del fichero
//            while ((linea = br.readLine()) != null) {
                lin = linea;
//            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            //en el finally cerramos el fichero, para asegurarnos
            //que se cierra tanto si todo va bien como si salta
            //una excepcion
            try {
                if (null != fr) {
                    fr.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
        return lin;
    }
    public String generaHTML(String[] imagenes){
            String txtHtml="";
            txtHtml += "<!DOCTYPE HTML>";
            txtHtml += "<html>";
            txtHtml += "	<head>";
            txtHtml += "	<meta charset=utf-8>";
            txtHtml += "		<title>Miniport by HTML5 UP</title>";
            txtHtml += "		<script src=\"js/jquery.min.js\"></script>";
            txtHtml += "		<script src=\"js/jquery.scrolly.min.js\"></script>";
            txtHtml += "		<script src=\"js/skel.min.js\"></script>";
            txtHtml += "		<script src=\"js/init.js\"></script>";
            txtHtml += "		<noscript>";
            txtHtml += "			<link rel=\"stylesheet\" href=\"css/skel.css\" />";
            txtHtml += "			<link rel=\"stylesheet\" href=\"css/style.css\" />";
            txtHtml += "			<link rel=\"stylesheet\" href=\"css/style-desktop.css\" />";
            txtHtml += "		</noscript>";
            txtHtml += "		<!--[if lte IE 8]><link rel=\"stylesheet\" href=\"css/ie/v8.css\" /><![endif]-->";
            txtHtml += "		<!--[if lte IE 9]><link rel=\"stylesheet\" href=\"css/ie/v9.css\" /><![endif]-->";
            txtHtml += "	</head>";
            txtHtml += "	<body>";
            txtHtml += "";
            txtHtml += "		<!-- Nav -->";
            txtHtml += "			<nav id=\"nav\">";
            txtHtml += "				<ul class=\"container\">";
            txtHtml += "					<li><a href=\"#contact\">Traductor de español a braile</a></li>";
            txtHtml += "				</ul>";
            txtHtml += "			</nav>";
            txtHtml += "";
            txtHtml += "		<!-- Work -->";
            txtHtml += "				";
            txtHtml += "		<!-- Contact -->";
            txtHtml += "			<div class=\"wrapper style4\">";
            txtHtml += "				<article id=\"contact\" class=\"container 75%\">";
            for (int i=0;i<imagenes.length;i++) {
                if(imagenes[i]!=null && imagenes[i]!="")
                txtHtml+="<img src=\"src\\javaapplication21\\imagenes\\"+imagenes[i]+"\" width=40 height=60>";
            }
            txtHtml += "				</article>";
            txtHtml += "			</div>";
            txtHtml += "";
            txtHtml += "	</body>";
            txtHtml += "</html>";

        return txtHtml;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            txtTraducir.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String txtTraduccion=txtTraducir.getText();
        if(txtTraduccion.equals(null) || txtTraduccion.equals("")){
           JOptionPane.showMessageDialog(null,"Ingrese algo a traducir");
            return;
        }
        txtTraduccion=txtTraduccion.toLowerCase();
        txtTraduccion=txtTraduccion.replaceAll("\n", " ");
        char letra[]=new char[10000];
                letra= txtTraduccion.toCharArray();
        Traductor t=new Traductor(letra);
        String[] imagenes =new String[10000];
                imagenes= t.getTraducidas();
        
        escribir(generaHTML(imagenes));
        JOptionPane.showMessageDialog(null,"Traducido correctamente");
        try {
            Runtime.getRuntime().exec("cmd /c start traductor.html");
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTraductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTraductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtTraducir;
    // End of variables declaration//GEN-END:variables
}
